//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcReservaHotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hab_reser
    {
        public int cod_hab_reser { get; set; }
        public Nullable<int> cod_habitacion { get; set; }
        public Nullable<int> cod_reservacion { get; set; }
    
        public virtual habitacion habitacion { get; set; }
        public virtual reservacion reservacion { get; set; }
    }
}
